[project]
name = "datastar-sanic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datastar-py>=0.5.0",
    "sanic>=25.3.0",
    "sanic-compress-plus>=0.1.1",
    "tinydb>=4.8.2",
]
